/**
 * AUTOGENERATED CODE BY export_accountitems.lua
 *
 * @packageDocumentation
 */

/**
 * Interface for beefalo clothing items.
 *
 * @interface BeefaloClothing
 * @property {string} type - The type of the clothing item.
 * @property {string[]} skin_tags - The skin tags associated with the clothing item.
 * @property {string[]} symbol_overrides - The symbol overrides for the clothing item.
 * @property {string[]} [symbol_hides] - The symbol hides for the clothing item.
 * @property {string} rarity - The rarity of the clothing item.
 * @property {number} release_group - The release group of the clothing item.
 */
interface BeefaloClothing {
  type: string;
  skin_tags: string[];
  symbol_overrides: string[];
  symbol_hides?: string[];
  rarity: string;
  release_group: number;
}

const BEEFALO_CLOTHING: { [key: string]: BeefaloClothing } = {
  beefalo_body_beast: {
    type: "beef_body",
    skin_tags: ["BEEFALO_BODY", "BEEFALO"],
    symbol_overrides: ["beefalo_body", "beefalo_body_heat"],
    rarity: "Complimentary",
    release_group: 112,
  },
  beefalo_body_doll: {
    type: "beef_body",
    skin_tags: ["BEEFALO_BODY", "BEEFALO"],
    symbol_overrides: ["beefalo_body", "beefalo_body_heat"],
    rarity: "Complimentary",
    release_group: 112,
  },
  beefalo_body_festive: {
    type: "beef_body",
    skin_tags: ["BEEFALO_BODY", "BEEFALO"],
    symbol_overrides: ["beefalo_body", "beefalo_body_heat"],
    rarity: "Complimentary",
    release_group: 112,
  },
  beefalo_body_formal: {
    type: "beef_body",
    skin_tags: ["BEEFALO_BODY", "BEEFALO"],
    symbol_overrides: ["beefalo_body", "beefalo_body_heat"],
    rarity: "Complimentary",
    release_group: 112,
  },
  beefalo_body_ice: {
    type: "beef_body",
    skin_tags: ["BEEFALO_BODY", "BEEFALO"],
    symbol_overrides: ["beefalo_body", "beefalo_body_heat"],
    rarity: "Complimentary",
    release_group: 112,
  },
  beefalo_body_nature: {
    type: "beef_body",
    skin_tags: ["BEEFALO_BODY", "BEEFALO"],
    symbol_overrides: ["beefalo_body", "beefalo_body_heat"],
    rarity: "Complimentary",
    release_group: 112,
  },
  beefalo_body_robot: {
    type: "beef_body",
    skin_tags: ["BEEFALO_BODY", "BEEFALO"],
    symbol_overrides: ["beefalo_body", "beefalo_body_heat"],
    rarity: "Complimentary",
    release_group: 112,
  },
  beefalo_body_victorian: {
    type: "beef_body",
    skin_tags: ["BEEFALO_BODY", "BEEFALO"],
    symbol_overrides: ["beefalo_body", "beefalo_body_heat"],
    rarity: "Complimentary",
    release_group: 112,
  },
  beefalo_body_war: {
    type: "beef_body",
    skin_tags: ["BEEFALO_BODY", "BEEFALO"],
    symbol_overrides: ["beefalo_body", "beefalo_body_heat"],
    rarity: "Complimentary",
    release_group: 112,
  },
  beefalo_feet_beast: {
    type: "beef_feet",
    skin_tags: ["BEEFALO_FEET", "BEEFALO"],
    symbol_overrides: ["beefalo_hoof"],
    rarity: "Complimentary",
    release_group: 112,
  },
  beefalo_feet_doll: {
    type: "beef_feet",
    skin_tags: ["BEEFALO_FEET", "BEEFALO"],
    symbol_overrides: ["beefalo_hoof"],
    rarity: "Complimentary",
    release_group: 112,
  },
  beefalo_feet_festive: {
    type: "beef_feet",
    skin_tags: ["BEEFALO_FEET", "BEEFALO"],
    symbol_overrides: ["beefalo_hoof"],
    rarity: "Complimentary",
    release_group: 112,
  },
  beefalo_feet_formal: {
    type: "beef_feet",
    skin_tags: ["BEEFALO_FEET", "BEEFALO"],
    symbol_overrides: ["beefalo_hoof"],
    rarity: "Complimentary",
    release_group: 112,
  },
  beefalo_feet_ice: {
    type: "beef_feet",
    skin_tags: ["BEEFALO_FEET", "BEEFALO"],
    symbol_overrides: ["beefalo_hoof"],
    rarity: "Complimentary",
    release_group: 112,
  },
  beefalo_feet_nature: {
    type: "beef_feet",
    skin_tags: ["BEEFALO_FEET", "BEEFALO"],
    symbol_overrides: ["beefalo_hoof"],
    rarity: "Complimentary",
    release_group: 112,
  },
  beefalo_feet_robot: {
    type: "beef_feet",
    skin_tags: ["BEEFALO_FEET", "BEEFALO"],
    symbol_overrides: ["beefalo_hoof"],
    rarity: "Complimentary",
    release_group: 112,
  },
  beefalo_feet_victorian: {
    type: "beef_feet",
    skin_tags: ["BEEFALO_FEET", "BEEFALO"],
    symbol_overrides: ["beefalo_hoof"],
    rarity: "Complimentary",
    release_group: 112,
  },
  beefalo_feet_war: {
    type: "beef_feet",
    skin_tags: ["BEEFALO_FEET", "BEEFALO"],
    symbol_overrides: ["beefalo_hoof"],
    rarity: "Complimentary",
    release_group: 112,
  },
  beefalo_head_beast: {
    type: "beef_head",
    skin_tags: ["BEEFALO_HEAD", "BEEFALO"],
    symbol_overrides: [
      "beefalo_beard",
      "beefalo_eye",
      "beefalo_facebase",
      "beefalo_headbase",
      "beefalo_jowls",
      "beefalo_lip_crease",
      "beefalo_mouthmouth",
      "beefalo_nose",
      "beffalo_lips",
    ],
    rarity: "Complimentary",
    release_group: 112,
  },
  beefalo_head_doll: {
    type: "beef_head",
    skin_tags: ["BEEFALO_HEAD", "BEEFALO"],
    symbol_overrides: [
      "beefalo_beard",
      "beefalo_facebase",
      "beefalo_headbase",
      "beefalo_jowls",
      "beefalo_lip_crease",
      "beefalo_mouthmouth",
      "beefalo_nose",
      "beffalo_lips",
    ],
    rarity: "Complimentary",
    release_group: 112,
  },
  beefalo_head_festive: {
    type: "beef_head",
    skin_tags: ["BEEFALO_HEAD", "BEEFALO"],
    symbol_overrides: [
      "beefalo_beard",
      "beefalo_facebase",
      "beefalo_headbase",
      "beefalo_jowls",
      "beefalo_lip_crease",
      "beefalo_mouthmouth",
      "beefalo_nose",
      "beffalo_lips",
    ],
    rarity: "Complimentary",
    release_group: 112,
  },
  beefalo_head_formal: {
    type: "beef_head",
    skin_tags: ["BEEFALO_HEAD", "BEEFALO"],
    symbol_overrides: [
      "beefalo_beard",
      "beefalo_facebase",
      "beefalo_headbase",
      "beefalo_jowls",
      "beefalo_lip_crease",
      "beefalo_mouthmouth",
      "beefalo_nose",
      "beffalo_lips",
    ],
    rarity: "Complimentary",
    release_group: 112,
  },
  beefalo_head_ice: {
    type: "beef_head",
    skin_tags: ["BEEFALO_HEAD", "BEEFALO"],
    symbol_overrides: [
      "beefalo_beard",
      "beefalo_facebase",
      "beefalo_headbase",
      "beefalo_jowls",
      "beefalo_lip_crease",
      "beefalo_mouthmouth",
      "beefalo_nose",
      "beffalo_lips",
    ],
    symbol_hides: ["beefalo_eye"],
    rarity: "Complimentary",
    release_group: 112,
  },
  beefalo_head_nature: {
    type: "beef_head",
    skin_tags: ["BEEFALO_HEAD", "BEEFALO"],
    symbol_overrides: [
      "beefalo_beard",
      "beefalo_facebase",
      "beefalo_headbase",
      "beefalo_jowls",
      "beefalo_lip_crease",
      "beefalo_mouthmouth",
      "beefalo_nose",
      "beffalo_lips",
    ],
    symbol_hides: ["beefalo_eye"],
    rarity: "Complimentary",
    release_group: 112,
  },
  beefalo_head_robot: {
    type: "beef_head",
    skin_tags: ["BEEFALO_HEAD", "BEEFALO"],
    symbol_overrides: [
      "beefalo_beard",
      "beefalo_facebase",
      "beefalo_headbase",
      "beefalo_jowls",
      "beefalo_lip_crease",
      "beefalo_mouthmouth",
      "beefalo_nose",
      "beffalo_lips",
    ],
    rarity: "Complimentary",
    release_group: 112,
  },
  beefalo_head_victorian: {
    type: "beef_head",
    skin_tags: ["BEEFALO_HEAD", "BEEFALO"],
    symbol_overrides: [
      "beefalo_beard",
      "beefalo_facebase",
      "beefalo_headbase",
      "beefalo_jowls",
      "beefalo_lip_crease",
      "beefalo_mouthmouth",
      "beefalo_nose",
      "beffalo_lips",
    ],
    rarity: "Complimentary",
    release_group: 112,
  },
  beefalo_head_war: {
    type: "beef_head",
    skin_tags: ["BEEFALO_HEAD", "BEEFALO"],
    symbol_overrides: [
      "beefalo_beard",
      "beefalo_facebase",
      "beefalo_headbase",
      "beefalo_jowls",
      "beefalo_lip_crease",
      "beefalo_mouthmouth",
      "beefalo_nose",
      "beffalo_lips",
    ],
    rarity: "Complimentary",
    release_group: 112,
  },
  beefalo_horn_beast: {
    type: "beef_horn",
    skin_tags: ["BEEFALO_HORN", "BEEFALO"],
    symbol_overrides: ["beefalo_antler"],
    rarity: "Complimentary",
    release_group: 112,
  },
  beefalo_horn_doll: {
    type: "beef_horn",
    skin_tags: ["BEEFALO_HORN", "BEEFALO"],
    symbol_overrides: ["beefalo_antler"],
    rarity: "Complimentary",
    release_group: 112,
  },
  beefalo_horn_festive: {
    type: "beef_horn",
    skin_tags: ["BEEFALO_HORN", "BEEFALO"],
    symbol_overrides: ["beefalo_antler"],
    rarity: "Complimentary",
    release_group: 112,
  },
  beefalo_horn_formal: {
    type: "beef_horn",
    skin_tags: ["BEEFALO_HORN", "BEEFALO"],
    symbol_overrides: ["beefalo_antler"],
    rarity: "Complimentary",
    release_group: 112,
  },
  beefalo_horn_ice: {
    type: "beef_horn",
    skin_tags: ["BEEFALO_HORN", "BEEFALO"],
    symbol_overrides: ["beefalo_antler"],
    rarity: "Complimentary",
    release_group: 112,
  },
  beefalo_horn_nature: {
    type: "beef_horn",
    skin_tags: ["BEEFALO_HORN", "BEEFALO"],
    symbol_overrides: ["beefalo_antler"],
    rarity: "Complimentary",
    release_group: 112,
  },
  beefalo_horn_robot: {
    type: "beef_horn",
    skin_tags: ["BEEFALO_HORN", "BEEFALO"],
    symbol_overrides: ["beefalo_antler"],
    rarity: "Complimentary",
    release_group: 112,
  },
  beefalo_horn_victorian: {
    type: "beef_horn",
    skin_tags: ["BEEFALO_HORN", "BEEFALO"],
    symbol_overrides: ["beefalo_antler"],
    rarity: "Complimentary",
    release_group: 112,
  },
  beefalo_horn_war: {
    type: "beef_horn",
    skin_tags: ["BEEFALO_HORN", "BEEFALO"],
    symbol_overrides: ["beefalo_antler"],
    rarity: "Complimentary",
    release_group: 112,
  },
  beefalo_tail_beast: {
    type: "beef_tail",
    skin_tags: ["BEEFALO_TAIL", "BEEFALO"],
    symbol_overrides: ["beefalo_tail"],
    rarity: "Complimentary",
    release_group: 112,
  },
  beefalo_tail_doll: {
    type: "beef_tail",
    skin_tags: ["BEEFALO_TAIL", "BEEFALO"],
    symbol_overrides: ["beefalo_tail"],
    rarity: "Complimentary",
    release_group: 112,
  },
  beefalo_tail_festive: {
    type: "beef_tail",
    skin_tags: ["BEEFALO_TAIL", "BEEFALO"],
    symbol_overrides: ["beefalo_tail"],
    rarity: "Complimentary",
    release_group: 112,
  },
  beefalo_tail_formal: {
    type: "beef_tail",
    skin_tags: ["BEEFALO_TAIL", "BEEFALO"],
    symbol_overrides: ["beefalo_tail"],
    rarity: "Complimentary",
    release_group: 112,
  },
  beefalo_tail_ice: {
    type: "beef_tail",
    skin_tags: ["BEEFALO_TAIL", "BEEFALO"],
    symbol_overrides: ["beefalo_tail"],
    rarity: "Complimentary",
    release_group: 112,
  },
  beefalo_tail_nature: {
    type: "beef_tail",
    skin_tags: ["BEEFALO_TAIL", "BEEFALO"],
    symbol_overrides: ["beefalo_tail"],
    rarity: "Complimentary",
    release_group: 112,
  },
  beefalo_tail_robot: {
    type: "beef_tail",
    skin_tags: ["BEEFALO_TAIL", "BEEFALO"],
    symbol_overrides: ["beefalo_tail"],
    rarity: "Complimentary",
    release_group: 112,
  },
  beefalo_tail_victorian: {
    type: "beef_tail",
    skin_tags: ["BEEFALO_TAIL", "BEEFALO"],
    symbol_overrides: ["beefalo_tail"],
    rarity: "Complimentary",
    release_group: 112,
  },
  beefalo_tail_war: {
    type: "beef_tail",
    skin_tags: ["BEEFALO_TAIL", "BEEFALO"],
    symbol_overrides: ["beefalo_tail"],
    rarity: "Complimentary",
    release_group: 112,
  },
};

/**
 * A map of Beefalo clothing symbols.
 */
export const BEEFALO_CLOTHING_SYMBOLS: Record<string, boolean> = {};

/**
 * A map of Beefalo hide symbols.
 */
export const BEEFALO_HIDE_SYMBOLS: Record<string, boolean> = {};

for (const v of Object.values(BEEFALO_CLOTHING)) {
  for (const sym of v.symbol_overrides) {
    BEEFALO_CLOTHING_SYMBOLS[sym] = true;
  }
  if (v.symbol_hides) {
    for (const sym of Object.values(v.symbol_hides)) {
      BEEFALO_HIDE_SYMBOLS[sym] = true;
    }
  }
}
