/**
 * AUTOGENERATED CODE BY export_accountitems.lua
 *
 * @packageDocumentation
 */

interface PrefabSkinIds {
  [key: string]: string;
}

interface PrefabSkins {
  [key: string]: string[];
}

const PREFAB_SKINS_IDS: { [key: string]: PrefabSkinIds } = {};
export const PREFAB_SKINS: PrefabSkins = {
  prefab1: ["skin1", "skin2"],
  prefab2: ["skin3", "skin4"],
};

for (const prefab in PREFAB_SKINS) {
  PREFAB_SKINS_IDS[prefab] = {};
  for (const index in PREFAB_SKINS[prefab]) {
    const skin = PREFAB_SKINS[prefab][index];
    PREFAB_SKINS_IDS[prefab][skin] = index;
  }
}
